#ifndef PINOUT_H
#define PINOUT_H

#define LIGHTS_POWER_PIN 2
#define LIGHTS_SPECTRUM_PIN 3
#define MAIN_PUMP_PIN 4
#define WATER_LEVEL_PIN_1 5
#define WATER_LEVEL_PIN_2 6


enum {LIGHTS_POWER=0,LIGHTS_SPECTRUM, CHEMICAL_1,CHEMICAL_2};

#endif // PINOUT_H
