#ifndef PINOUT_H
#define PINOUT_H

// PWM multiplexed

#define CHEM_LEVEL_PIN 0

#define LIGHTS_POWER_PIN 101
#define LIGHTS_SPECTRUM_PIN 102
#define MAIN_PUMP_PIN 103
#define MAIN_VALVE_PIN 104
#define HEIGH_LIFTER_PWM 105
#define HEIGH_LIFTER_DIR 106
#define HUMIDIFIER_PIN 107
#define WIND_POWER_PIN 108
#define WIND_ROTATION_PIN 109
#define CO2_INJECTOR_PIN 110

#define CHEM_MIX_1_PIN 107
#define CHEM_PUMP_1_PIN 108
#define CHEM_MIX_2_PIN 109
#define CHEM_PUMP_2_PIN 110
#define CHEM_MIX_3_PIN 111
#define CHEM_PUMP_3_PIN 112

#define WATER_LEVEL_PIN_1 1
#define WATER_LEVEL_PIN_2 2
#define HEIGH_TRIG_PRIN 4
#define HEIGH_ECHO_PIN 5

//Analog pins
#define TEMP_1_PIN 1
#define TEMP_2_PIN 2
#define HUMIDTY_PIN 3
#define TEMP_4_PIN 4
#define CO2_SENSOR_PIN 5

enum {LIGHTS_DAY=0,
      LIGHTS_SLEEP,
      LIGHTS_SPECTRUM,
      TEMPERATURE_AIR,
      HUMIDITY_AIR,
      TEMPERATURE_WATER,
      LIGHT_HEIGH,
      CO2_LEVEL,
      WIND_LEVEL,
      WIND_ROTATION,
      PH_LEVEL,
      CHEMICAL_1,
      CHEMICAL_2
};

#endif // PINOUT_H
